### ISSUE TITLE
Option for number of spaces used in gradle indentations

### ISSUE THREAD

**Issue by bigbass1997** [tommyettinger/gdx-liftoff#1]
For those, like me, who much prefer larger indentations (typically 4 spaces, or tabs), it would be nice to have an option in the GUI to define the indentation size used in the various generated gradle files.

As of right now, gradle files are created with 2 spaces per indent. In my experience, this is quite uncommon. Even the default project created by `gradle init --type java-application` uses 4 spaces per indent.

> "[...] I'd also change it to 4 spaces, 2 make my eyes bleed haha"
> -RafaSKB on Discord

**Comment by MrStahlfelge** [comment]
Not needed imo. You can use your IDE's autoformatter to change this to your preferred format.

**Comment by bigbass1997** [comment]
That is more work for the developer though. The whole point of this program is to setup stuff automatically for the developer. Additionally, what if you open the file in a different program like Notepad++ or push to github..

Regardless, I don't even see why it is 2 spaces by default in the first place. The old setup ui didn't do this, and gradle itself doesn't either.

Additionally, why not give the option to the developer? Just because something may not be _needed_, doesn't mean it shouldn't be added.

**Comment by tommyettinger** [comment]
I'll probably attempt to change the generated files to use a tab instead of two spaces. It saves a tiny amount of bandwidth! And since tabs can be interpreted as soft tabs by users who prefer spaces, or with variable width, that saves me some effort making a non-functionality-related configuration option.

As to why we shouldn't give the option to the developer, the app is already close to risking analysis paralysis from having a lot of options just for the functional behavior of the application. Should I allow zero indentation as an option? Are tabs a radio button that disables the number of spaces, or should peculiar users be allowed to use 23 tabs instead of what is now 2 spaces? An infinitely configurable tool would take infinite time to go through the options and make sure that some rule like brace placement wasn't just slightly wrong (after all, braces need to be separated from the previous keyword by two tabs, a space, a newline, and three more spaces, that's just how some people like their projects configured)...
