### ISSUE TITLE
Compilation errors in template MVC + Box2d

### ISSUE THREAD

**Issue by jeltedeproft** [tommyettinger/gdx-liftoff#118]
![image](https://user-images.githubusercontent.com/22193978/218415781-a35d99bc-0892-489c-88bd-02613da5a6f6.png)

The class PovDirection isnt found in this template

**Comment by tommyettinger** [comment]
Looking into it...

**Comment by tommyettinger** [comment]
OK, this should work now. You can comment out or delete anything that takes or uses a PovDirection, since it just doesn't exist in the current gdx-controllers. That would be the getX(PovDirection), getY(PovDirection), getAbsoluteX(PovDirection), and getAbsoluteY(PovDirection) methods in the class you showed.
