### ISSUE TITLE
gwt-module.dtd Not found

### ISSUE THREAD

**Issue by JojoIce** [tommyettinger/gdx-liftoff#135]
Creating a new project with HTML platform will result in errors in the gwt.xml files:

`Error while downloading 'http://www.gwtproject.org/doctype/2.10.0/gwt-module.dtd' to '/path/.lemminx/cache/http/www.gwtproject.org/doctype/2.10.0/gwt-module.dtd' : '[java.io.FileNotFoundException] https://www.gwtproject.org/doctype/2.10.0/gwt-module.dtd with code: 404 Not Found'.`

Version 2.10.0 is not there.

https://github.com/gwtproject/gwt/issues/9770

Possibly revert to 2.9 for now?

**Comment by tommyettinger** [comment]
I think I fixed this a few days ago! I'll double-check.

What we currently use (or will use as of the next release) is:

```
<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit ${project.advanced.gwtVersion}//EN" "https://www.gwtproject.org/doctype/2.8.2/gwt-module.dtd">
```
Where the gwtVersion is almost always 2.10.0 . I knew the GWT people didn't put up a 2.10.0 DTD when 2.10.0 was released, but it was a rocky release if I remember it correctly, and a number of things needed attention. I had switched to 2.8.2 because I knew it worked; I'm not sure if anything is different in 2.9.0 .

I commented on the GWT issue, also, mentioning that the 2.10.0 DTD gives a 404 (other versions don't).

**Comment by tommyettinger** [comment]
OK, the latest release should use the 2.8.2 DTD because I know that works. The 2.9.0 one probably works also, but might be the same...? I'm still planning on using the 2.10.0 DTD when it becomes available, which might be this decade.
