### ISSUE TITLE
Add Fleks to third party libraries?

### ISSUE THREAD

**Issue by Quillraven** [tommyettinger/gdx-liftoff#137]
As discussed on the Fleks repository, can you please add [Fleks](https://github.com/Quillraven/Fleks) as a third party library to gdx-liftoff?

Is there a guide on how to add a library? If so, then I can provide a PR, if you want.

Btw.: unrelated to this topic but I still get "duplicated folder warning for assets folder" when I have desktop + android backend. Most likely related to AGP and it is just a warning. Everything is still working. But do you have a solution how to remove the warning? Or is that simply impossible? :D

**Comment by tommyettinger** [comment]
There isn't a guide, but it's rather easy for a library with one dependency like Fleks! Something like artemis-odb, which requires a bunch of special treatment to work on GWT, would need stuff a normal guide wouldn't cover, but since Fleks only works with Kotlin, it doesn't need GWT-specialized configuration. Mostly to add new libraries, you copy an existing block for a library, change the default values to match the new library, and add some entries to the translation files (even though they are currently US-English-only). This was easy enough that I was done with this before I could reply, so here I am replying now.

As for the "duplicated folder warning for assets folder," I don't know what causes it, and I think gdx-setup projects have it too now. There may be a way to suppress the warning from Gradle files, but I wouldn't know where to start looking.
