### ISSUE TITLE
Default build does not work for 'html' module

### ISSUE THREAD

**Issue by Mr00Anderson** [tommyettinger/gdx-liftoff#14]
When running a just created liftoff project and running `html:superDev` results in the exception below. 

```
Task :html:draftCompileGwt FAILED
Loading inherited module 'com.virtual_hex.games.freeuniverse.GdxDefinitionSuperdev'
   Loading inherited module 'com.virtual_hex.games.freeuniverse.GdxDefinition'
      Loading inherited module 'com.virtual_hex.games.freeuniverse.Shared'
         [ERROR] Unable to find 'com/virtual_hex/games/freeuniverse/Shared.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

The resolution is to update this block
```
task addSource {
    doLast {
        sourceSets.main.compileClasspath += files(project(':core').sourceSets.main.allJava.srcDirs)
        sourceSets.main.compileClasspath += files(project(':shared').sourceSets.main.allJava.srcDirs)
    }
}
```

 in the `html` modules `build.gradle`.

**Comment by tommyettinger** [comment]
I've never actually used the `shared` project and I'm not totally sure what it was originally meant for (I think code that is used by both client and server). I am guessing this affects more than `html` but only when `shared` is in use. This is more of a bug in `shared` than in `html`, because you can create a default build of the `html` module just fine without `shared`.
