### ISSUE TITLE
HiDPI

### ISSUE THREAD

**Issue by Hangman** [tommyettinger/gdx-liftoff#17]
The UI is too small on HiDPI screens.
![size](https://user-images.githubusercontent.com/108926/85189306-213e3500-b2ae-11ea-981d-471b9f69ed28.png)
HiDPI support would be much appreciated :)

**Comment by tommyettinger** [comment]
Oh boy, yeah... this could be a problem to test because I don't have a HiDPI screen. I know that it's a problem if the text is too small, but just doubling the size of the font will make it pixelated. Would that be hard to read, or easier... I don't know.  I'll try a very naive approach with StretchViewport or something like it so people can at least enlarge the window and approximately enlarge the text.

**Comment by tommyettinger** [comment]
So I have a halfway-decent fix for this: use a much larger font with linear scaling, use a StretchViewport, allow the window to be resized. This yields larger views like https://i.imgur.com/EETCROn.png and even https://i.imgur.com/ETDOODl.png , without losing too much font quality. I still need to get the font a bit... better, unless people are fine with this. Normally on non-HDPI screens, it looks like https://i.imgur.com/1Tp88oq.png .

**Comment by tommyettinger** [comment]
If the latest release, https://github.com/tommyettinger/gdx-liftoff/releases/tag/v1.9.10.11 , doesn't fix this for you, please reopen or let me know.

**Comment by payne911** [comment]
Maybe a ``FitViewport`` would be a better approach?

https://github.com/libgdx/libgdx/wiki/Viewports#fitviewport

**Comment by tommyettinger** [comment]
@payne911 I'll try it now; I hope I don't cause any merge conflicts with in-progress PRs.

**Comment by payne911** [comment]
![image](https://user-images.githubusercontent.com/38117856/91935060-cf0c8d80-ecba-11ea-9e36-03753166e328.png)

Fixed #20 !
