### ISSUE TITLE
Selected destination is not a directory

### ISSUE THREAD

**Issue by AldieNightStar** [tommyettinger/gdx-liftoff#202]
- When i entered my SDK location (Folder is existing),
  - `<USER>` is replaced by user in the system
  - I see this red message: `Selected destination is not a directory`
```
C:\Users\<USER>\AppData\Local\Android\Sdk
```

## How to reproduce
- Be on `windows`
- Specify similar folder

# Resolved
- Need also create folder by hands for project and make sure all two folders existing

**Comment by tommyettinger** [comment]
I'm wondering if this is related to a known LWJGL3-related issue with non-alphanumeric characters in the username. I believe spaces, some punctuation, and any letters not used by English can cause problems with some libraries we know finding various things in the user's folder. There's a workaround applied for the native libraries so they don't get extracted in the user directory. There isn't one applied for Android SDK installations in the user dir if the username is unexpectedly non-alphanumeric.

I don't know exactly what happened here because your steps to reproduce don't cause that behavior for anyone else so far. You do need to have the Android SDK installed to make Android apps, of course. Installing Android Studio should get the required tools all put into the right places.
