### ISSUE TITLE
Everything is tiny.

### ISSUE THREAD

**Issue by travisfw** [tommyettinger/gdx-liftoff#27]
I need to squint and lean in to read everything, and I have pretty good eyes. My OS is Fedora 32, on a Dell XPS 9370, which has a fairly high pixel density. This is really not a common issue for me, though.

**Comment by tommyettinger** [comment]
This is fixable by resizing the window, or at least it should be fixed by that. I don't have any PC with very high DPI, so I can't test locally, but another issue reported problems with HDPI screens and the fix was to allow users to resize however they pleased, stretching the UI accordingly. Since then, the aspect ratio has been set so it won't change, but the screen can still resize, scaling UI uniformly. Please let me know if resizing works as expected; I think you've been on the libGDX Discord, so I'd appreciate if you could report back there or here at your convenience.

**Comment by tommyettinger** [comment]
11 days later, I can only assume silence means you aren't using liftoff or have found the fix I mentioned. Closing the issue; it should be resolved already by resizing the window.
