### ISSUE TITLE
Tool Not Working On Mac OS Catalina

### ISSUE THREAD

**Issue by arkadeepde142** [tommyettinger/gdx-liftoff#3]
[hs_err_pid908.log](https://github.com/tommyettinger/gdx-liftoff/files/4385513/hs_err_pid908.log)
Log file is attached.

**Comment by tommyettinger** [comment]
I can't really do a thing when someone says "not working." Please, give a description of the problem. Does any window appear, for any amount of time? If you launch from Terminal.app using `java -jar gdx-liftoff-1.9.10.4.jar` , is anything printed?

I can tell from the log that this is using LWJGL3, but not much else because there isn't very much I can discover from just the log. I was thinking that the problem could be related to a mismatch between gdx-tools' dependency on LWJGL2 and the GUI's dependency on LWJGL3, so I made a bunch of changes to fix that, and I just released them:

https://github.com/tommyettinger/gdx-liftoff/releases/tag/v1.9.10.5

I don't have any Mac to test on, and I have no idea what problem you've experienced or if this release fixes it.

**Comment by tommyettinger** [comment]
Closing after a month with no useful information.
