### ISSUE TITLE
Tooltip got stuck

### ISSUE THREAD

**Issue by raeleus** [tommyettinger/gdx-liftoff#34]
Hello. I'm not sure how I got this to happen:
![image](https://user-images.githubusercontent.com/12948924/97124349-f5640d80-16ec-11eb-8ecd-5bab01bee264.png)
I was just browsing the third party extension and the kotlin tooltip came up. I don't think I was mousing over the offending target, but it still came up on its own. It won't dismiss itself.

**Comment by tommyettinger** [comment]
I'm not sure tooltips ever work 100% using libGDX... I don't know of a good replacement, though. I don't think I've touched tooltip code; this may be a bug in the recent 1.9.12-SNAPSHOT of libGDX the latest release uses, or it could be a rare long-standing bug. I don't know how I could reproduce this, and I can't think of any workarounds I could suggest.

Leaving this open for a while to see if the bug comes back.

**Comment by raeleus** [comment]
Yeah, I wrote my own class to implement tooltips in my project. Not something I recommend here. I'll see if I can reproduce in a basic project. Thanks!

**Comment by tommyettinger** [comment]
I believe this is fixed now that #59 was merged.

**Comment by czyzby** [comment]
To be honest, I think that VisUI/LML tooltips can get stuck in recent libGDX versions, so I wouldn't close this without further testing. It might still be possible to reproduce, e.g. by switching windows with `ALT + TAB` while the tooltips are shown. It would probably be best to migrate to libGDX tooltips to avoid this, assuming they work correctly.
