### ISSUE TITLE
Auto-Fill Android SDK path with ANDROID_HOME environment variable

### ISSUE THREAD

**Issue by coolultra1** [tommyettinger/gdx-liftoff#48]
It'd be pretty nice to have.

**Comment by tommyettinger** [comment]
Yeah, it would, hm... I'll have to see what steps I would need to do, but it shouldn't be too much.

**Comment by tommyettinger** [comment]
I'm not sure if this is fixed for all machines, but I addressed this at least partially in September. The Android SDK path is loaded from Preferences if it has ever been set before, so this mainly matters on the first run (when Preferences are empty). I'm loading the ANDROID_SDK_ROOT variable, which is set by Android Studio in its current versions (last I checked), instead of ANDROID_HOME, which is not set by any current installers that I could find. If anyone still has issues with this, like a wildly incorrect path being used at the start or continually used on multiple runs, please comment and I can reopen.
