### ISSUE TITLE
Kotlin dsl and AGP and b2d-light version update

### ISSUE THREAD

**Issue by Quillraven** [tommyettinger/gdx-liftoff#5]
Hi,

first of all: thank you a lot for this setup. It produces a much better and more modern result than the one from libgdx.

I would like to ask three things, if possible:
1) android gradle plugin can be increased to 3.6.0 from 3.5.0 in my opinion
2) box2d light version can be increased from 1.4 to 1.5
3) when I select "kotlin" as a language it would be great if it produces `build.gradle.kts` and `settings.gradle.kts` files

I think nothing of that is super urgent but would be great if that gets changed. Also, is there a reason why you did not use the `buildSrc` folder approach and instead you define the versions in gradle.properties file? This is just a question out of interest, why you choose that approach over the other :)

**Comment by Quillraven** [comment]
I provided an example project with kotlin dsl for android and desktop which was initially setup with your setup jar and then converted to kotlin gradle.dsl to my best knowledge.

Also, converted the launcher and game class to kotlin and moved them to the kotlin src folder.

[Dark Matter.zip](https://github.com/tommyettinger/gdx-liftoff/files/4465117/Dark.Matter.zip)

**Comment by tommyettinger** [comment]
I'll take a look; I'm somewhat suspicious of Kotlin platform launchers because so many issues have been reported on the Discord related to people translating DesktopLauncher.java to DesktopLauncher.kt . If it can be generated with an optimal setup from the start, that might help avoid those errors. Having the Game class in Kotlin would be better than having it in Java, yeah.

I'll update Android Gradle plugin and Box2D right away.

I actually like the gradle.properties approach, since it keeps versions centralized in one file, but that wasn't my idea; I forked this from czyzby's gdx-setup, which used gradle.properties for versions.

**Comment by Quillraven** [comment]
@tommyettinger I think we can close this issue. If you are interested in kotlin dsl gradle files then please refer to this project: https://github.com/Quillraven/Dark-Matter

I started with your setup (as mentioned in Readme.md ;)) and adjusted the gradle files accordingly. I was able to successfully build the desktop jar and deploy on android.

From time to time you get the "DesktopLauncher blabla" missing when you run it. But I guess this is somehow a bug related to kotlin or intellij or gradle or the combination of them. Simply running the application again fixes it, so I guess it is sometimes a timing issue with building and running.

**Comment by tommyettinger** [comment]
OK, I'll close then. I'm just not quite comfortable with the interactions between Kotlin and the many parts of a Gradle build, so I don't feel like I could reasonably maintain this kind of code myself.  Could I put a link to your Dark-Matter project in the Readme.md so people who want to use Kotlin can see more fully how you did that?

**Comment by Quillraven** [comment]
If you want, you can link it of course - thanks!
