### ISSUE TITLE
Grab scroll focus on mouse over.

### ISSUE THREAD

**Issue by raeleus** [tommyettinger/gdx-liftoff#8]
As a new user to your excellent GDX Liftoff, there is only one nagging issue I have with the UI. Scroll focus isn't assigned to scroll panes unless you click on them first. It would be much more convenient if it automatically grabbed focus when the mouse is over the widget. Thank you for your help.

**Comment by tommyettinger** [comment]
How would I do this? As far as I understand, this is a known issue in libGDX; do you know of a workaround? Unfortunately in some ways, this project uses vis-ui, and since I had forked the project off of czyzby's setup tool, I don't understand a lot of its nuances very well. It looks nice though.

I'd be perfectly willing to add you as a contributor if you wanted to clean up the (probably quite messy) GUI code. I'm sure we'd all learn valuable lessons about making our own XML-based markup formats.

**Comment by raeleus** [comment]
I was in the middle of forking your project and starting a pull request to start making additions when I realized you crazy cats use Kotlin. You've found my kryptonite, sir. Anyway, the fix is simple. You just need to add this listener to your scroll panes: https://github.com/raeleus/skin-composer/blob/dev/core/src/com/ray3k/skincomposer/ScrollFocusListener.java

In all honesty, my GUI code is generally messy too. With a project like this, I would prefer to write it from scratch in a way that I would understand it. My disdain for VisUI also wouldn't be helpful either...
