### ISSUE TITLE
Request to add gdx-psx to third-party libraries

### ISSUE THREAD

**Issue by fxgaming** [tommyettinger/gdx-liftoff#80]
asking for adding [gdx-psx](https://github.com/fxgaming/gdx-psx) to the third-party libraries

**Comment by tommyettinger** [comment]
I would like to, but your JitPack builds for the latest several commits are all entirely broken (only a sources jar is provided, no compiled code). A sources jar would be enough if the library only ever supported GWT, maybe, but it doesn't support GWT at all, so that won't do. I don't think I can force a JitPack release to be used with the current setup; I can force a Maven Central release to use the latest one there, but Maven Central is a significant hassle to start with. My recommendation is to fix your JitPack build so it produces a jar for the class files, for the docs, and for the sources. I make [a library template](https://github.com/tommyettinger/libgdx-library-template) for this exact purpose, including JitPack configuration.

As an aside, you should really have a `.gitignore` file (maybe also `.gitattributes`) that is configured so things like your binary `.class` files in `bin` won't get committed. There's no point in having .class files in the source code of a repo. The library template above includes `.gitignore` configuration that will ignore changes to those files, though you should delete all of the .class files from a repo before adding them to `.gitignore`.

**Comment by tommyettinger** [comment]
It looks like all of this has been taken care of now, thanks to @lyze237 's PRs, so I just added gdx-psx to the latest commit. JitPack may still be temperamental about version ordering, but there isn't much we can do about that except wait and see if it stays working (it does work now).
