### ISSUE TITLE
Proguard for desktop

### ISSUE THREAD

**Issue by Zanzibahhh** [tommyettinger/gdx-liftoff#81]
It would be great if the desktop projects could be pre-configured with Proguard obfuscation.

**Comment by tommyettinger** [comment]
ProGuard is honestly kind of a mess to set up automatically. I really have no idea how I would do this with library versions that update and don't include automated instructions for ProGuard (and I don't think there are any kinds of such instructions out there...). So I agree that it would be great, but I don't think it's within the scope of this project, if it is even feasible for any project generator.

I'm closing this now because I don't think it's possible to accomplish; if anyone has any links to existing projects that are able to configure ProGuard for arbitrary libraries at arbitrary versions, please comment here and I will reopen.
