### ISSUE TITLE
Suggestion: Include option to generate lwjgl3 module with jpackage/packr support

### ISSUE THREAD

**Issue by lyze237** [tommyettinger/gdx-liftoff#86]
Hey!

It would be fantastic if we would have two options to add support for jpackage or packr!

For jpackage you can use the following gralde file as reference (Though it's missing macos stuff): <https://github.com/lyze237-gamejams/FireAndIce/blob/master/lwjgl3/build.gradle>

And for packr I guess we could make a task which downloads packr and runs it with the appropriate settings?

This would make it very easy to package the app as an .exe and would improve game jams and generally everything a bit!

**Comment by tommyettinger** [comment]
Hmm... So, jpackage would need JDK 14 or higher, though it has no real effect on required language level (still 8+ for LWJGL3). Packr would be nice to support too, but I have no experience with the current packr version. I'm reluctant to do much downloading within Liftoff, because it seems like it could result in large downloads being done several times or more. I think jpackage is probably fine even without gh-actions support, though it would be nice to be able to auto-build Windows/MacOS/Linux builds on a tag or release.

I'll take a look into this, and your FireAndIce config.

**Comment by tommyettinger** [comment]
I had some jpackageimage configuration in CaveCops, with what I think is still valid MacOS packaging. New projects have what is essentially that configuration copied in in a conditional block, so it only runs if using Java 14 or higher. I can look into adding gh-actions support to new projects, but I have never used gh-actions, so I'm kinda lost. If you're interested in trying out a Liftoff build with this, [I posted this beta JAR to Discord](https://cdn.discordapp.com/attachments/930602599151968256/983664973060399155/gdx-liftoff-1.11.0.1beta-jpackage.jar) , and asked people to try it there.

**Comment by tommyettinger** [comment]
I've been waiting for Gradle 7.5 to come out, which should be any week now, to release the latest changes to gdx-liftoff. This includes jpackage support when running on a high enough JDK version! I'm pretty sure it works now! I'll close this when the release is actually out.

**Comment by tommyettinger** [comment]
Oh yeah, the release has been out for months, and I'm pretty sure the jpackage stuff works in most places. I'll close now.
