### ISSUE TITLE
How about adding an option to import the Imgui for libgdx?

### ISSUE THREAD

**Issue by tehnewb** [tommyettinger/gdx-liftoff#98]
Considering there is so many frustrating issues with attempting to get imgui to work with libgdx, especially with newer java or gradle versions, can there be added an option to add imgui as a third-party dependency?

**Comment by tommyettinger** [comment]
I already tried this, and it is just as frustrating here. I have some imgui config commented out; it is preceded by this comment:
```kt
//    /**
//     * An immediate-mode GUI library (LWJGL3-only!) that can be an alternative to scene2d.ui.
//     * NOTE: this is only accessible from the lwjgl3 project, and may require unusual
//     * project configuration to use.
//     * @author SpaiR
//     */
```
Essentially, having imgui as a dependency forces either all of your project to be in one (lwjgl3) module, or to have a really complex system of many interfaces to replace imgui on non-LWJGL3 platforms where it isn't available. I think any project that is so dead-set on avoiding built-in cross-platform scene2d.ui can afford to do some extra configuration to set up, since everything it does with imgui is going to take more work to get started... The sheer amount of differences between a typical libGDX project and one that uses imgui make supporting imgui in a typical libGDX project generator somewhat of a futile effort.

I'm going to close this because I tried it already and it wasn't tenable. If you have any ideas for how to make imgui work in a normal multi-module libGDX structure, feel free to comment and I can reopen if you think of something that might work.
